sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start Creating an image with dockerfile"
  - docker build -t jheehg/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true jheehg/docker-react-app npm run test -- --coverage

deploy:
  edge: true
  provider: elasticbeanstalk
  region: 'ap-northeast-1'
  app: 'docker-react-app'
  env: 'Dockerreactapp-env'
  bucket_name: 'elasticbeanstalk-ap-northeast-1-817125338718'
  bucket_path: 'docker-react-app'
  on:
    branch: master

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
